Creative_blog/Models/Stat.cs
using System.ComponentModel.DataAnnotations;

namespace Creative_blog.Models
{
    public class Stat : BaseEntity
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public int Count { get; set; }
        [Required]
        public string Icon { get; set; }
    }
}

Creative_blog/Areas/AdminArea/Controllers/StatController.cs
using Creative_blog.Data;
using Creative_blog.Helpers.Enums;
using Creative_blog.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Creative_blog.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize(Roles = "Admin")]
    public class StatController : Controller
    {
        private readonly AppDbContext _context;
        public StatController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Stats.Where(m => !m.IsDeleted).ToListAsync());
        }

        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Stat stat)
        {
            if (!ModelState.IsValid) return View();

            Stat newStat = new Stat
            {
                Icon = stat.Icon,
                Name = stat.Name,
                Count = stat.Count  
            };

            await _context.Stats.AddAsync(newStat);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null) return BadRequest();

            Stat stat = await GetByIdAsync((int)id);

            if (stat == null) return NotFound();

            return View(stat);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, Stat stat)
        {
            if (id is null) return BadRequest();

            var dbStat = await GetByIdAsync((int)id);

            if (dbStat == null) return NotFound();

            dbStat.Icon = stat.Icon;
            dbStat.Name = stat.Name;
            dbStat.Count = stat.Count;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id is null) return BadRequest();

            Stat stat = await GetByIdAsync((int)id);

            if (stat == null) return NotFound();

            return View(stat);
        }

        public async Task<IActionResult> Delete(int id)
        {
            Stat stat = await GetByIdAsync(id);

            if (stat == null) return NotFound();


            stat.IsDeleted = true;

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }















        private async Task<Stat> GetByIdAsync(int id)
        {
            return await _context.Stats.FindAsync(id);
        }
    }
}

Creative_blog/Areas/AdminArea/Views/Stat/Create.cshtml
@model Stat
@{
    ViewData["Title"] = "Create";
}



<div class="container-fluid mx-5 my-3">
    <h3>Service</h3>
    <form asp-action="Create" method="post" enctype="multipart/form-data">
        <div class="form-group">

            <label for="Icon">Icon</label>
            <input class="form-control" asp-for="Icon">
            <span class="text-danger" asp-validation-for="Icon"></span>

            <label for="Name">Name</label>
            <input class="form-control" asp-for="Name">
            <span class="text-danger" asp-validation-for="Name"></span>

            <label for="Count">Count</label>
            <input type="number" class="form-control" asp-for="Count">
            <span class="text-danger" asp-validation-for="Count"></span>


        </div>
        <a class="btn btn-primary" asp-controller="Stat" asp-action="Index">Back</a>
        <a class="btn btn-primary" asp-controller="Stat" asp-action="Create">Reset</a>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

Creative_blog/Areas/AdminArea/Views/Stat/Detail.cshtml
@model Stat
@{
    ViewData["Title"] = "Detail";
}

<div class="container">
    <div class="container-fluid my-3 mx-3">
        <div class="table-responsive pt-3">

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            Icon
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Count
                        </th>


                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <div class="box-item">
                                <i class="@Model.Icon"></i>

                            </div>
                        </td>
                        <td>
                            @Model.Name
                        </td>



                        <td>
                            @Model.Count
                        </td>


                    </tr>


                </tbody>
            </table>
        </div>
    </div>
</div>

Creative_blog/Areas/AdminArea/Views/Stat/Edit.cshtml
@model Stat
@{
    ViewData["Title"] = "Create";
}



<div class="container-fluid mx-5 my-3">
    <h3>Service Edit</h3>
    <form asp-action="Edit" method="post" enctype="multipart/form-data">
        <div class="form-group">

            <label for="Icon">Icon</label>
            <input class="form-control" asp-for="Icon">
            <span class="text-danger" asp-validation-for="Icon"></span>

            <label for="Name">Name</label>
            <input class="form-control" asp-for="Name">
            <span class="text-danger" asp-validation-for="Name"></span>

            <label for="Count">Count</label>
            <input type="number" class="form-control" asp-for="Count">
            <span class="text-danger" asp-validation-for="Count"></span>


        </div>
        <a class="btn btn-primary" asp-controller="Stat" asp-action="Index">Back</a>
        <a class="btn btn-primary" asp-controller="Stat" asp-action="Create">Reset</a>
        <button type="submit" class="btn btn-primary">Edit</button>
    </form>
</div>

Creative_blog/Areas/AdminArea/Views/Stat/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="container-fluid my-3 mx-3">
        <div class="table-responsive pt-3">
            <div class="create-btn mb-3">
                <a asp-area="AdminArea" asp-controller="Stat" asp-action="Create" class="btn btn-success"><i class="fa-solid fa-plus"><h1></h1></i></a>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            Icon
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Count
                        </th>


                        <th style="text-align: center;">
                            Settings
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <div class="box-item">
                                    <i class="@item.Icon"></i>

                                </div>



                            </td>

                            <td>
                                @item.Name
                            </td>



                            <td>
                                @item.Count
                            </td>

                            <td style="text-align: center;">
                                <a asp-action="Detail" asp-route-id="@item.Id" class="btn btn-primary"><i class="mdi mdi-information mx-0">D</i></a>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary"><i class="mdi mdi-table-edit"></i>E</a>
                                <form style="display: inline-block;" asp-action="Delete" asp-route-id="@item.Id" method="post">
                                    <button type="submit" class="btn btn-danger"><i class="mdi mdi-delete-forever"></i>R</button>
                                </form>
                            </td>
                        </tr>

                    }

                </tbody>
            </table>
        </div>
    </div>
</div>