Creative_blog/Models/OurService.cs
using System.ComponentModel.DataAnnotations;

namespace Creative_blog.Models
{
    public class OurService : BaseEntity
    {
        [Required]
        public string Icon { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Desc { get; set; }
    }
}

Creative_blog/Areas/AdminArea/Controllers/OurServiceController.cs
using Creative_blog.Data;
using Creative_blog.Helpers;
using Creative_blog.Models;
using Creative_blog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Creative_blog.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize(Roles = "Admin")]
    public class OurServiceController : Controller
    {
        private readonly AppDbContext _context;
        public OurServiceController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int page = 1, int take = 4)
        {
            List<OurService> ourServices = await _context.OurServices
                .Where(m => !m.IsDeleted)
                .Skip((page * take) - take)
                .Take(take).ToListAsync();

            List<OurServiceListVM> mapDatas = GetMapDatas(ourServices);

            int count = await GetPageCount(take);

            Paginate<OurServiceListVM> result = new Paginate<OurServiceListVM>(mapDatas,page,count);


            return View(result);

           


        }


        public async Task<int> GetPageCount(int take)
        {
            int productCount = await _context.OurServices.Where(m => !m.IsDeleted).CountAsync();

            return (int)Math.Ceiling((decimal)productCount / take);
        }


        private List<OurServiceListVM> GetMapDatas(List<OurService> ourServices)
        {
            List<OurServiceListVM> ourServiceList = new List<OurServiceListVM>();
            foreach (var ourService in ourServices)
            {
                OurServiceListVM newOurService = new OurServiceListVM
                {
                    Id = ourService.Id,
                    Icon = ourService.Icon,
                    Desc = ourService.Desc,
                    Name = ourService.Name
                };
                ourServiceList.Add(newOurService);
            }
            return ourServiceList;
        }





















        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OurService ourService)
        {
            if (!ModelState.IsValid) return View();

            OurService newOurService = new OurService
            {
                Icon = ourService.Icon,
                Name = ourService.Name,
                Desc = ourService.Desc
            };

            await _context.OurServices.AddAsync(newOurService);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null) return BadRequest();

            OurService ourService = await GetByIdAsync((int)id);

            if (ourService == null) return NotFound();

            return View(ourService);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, OurService ourService)
        {
            if (id is null) return BadRequest();

            var dbOurService = await GetByIdAsync((int)id);

            if (dbOurService == null) return NotFound();

            dbOurService.Icon = ourService.Icon;
            dbOurService.Name = ourService.Name;
            dbOurService.Desc = ourService.Desc;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id is null) return BadRequest();

            OurService ourService = await GetByIdAsync((int)id);

            if (ourService == null) return NotFound();

            return View(ourService);
        }

        public async Task<IActionResult> Delete(int id)
        {
            OurService ourService = await GetByIdAsync(id);

            if (ourService == null) return NotFound();


            ourService.IsDeleted = true;

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }




        private async Task<OurService> GetByIdAsync(int id)
        {
            return await _context.OurServices.FindAsync(id);
        }
    }
}

Creative_blog/Areas/AdminArea/Views/OurService/Create.cshtml
@model OurService
@{
    ViewData["Title"] = "Create";
}



<div class="container-fluid mx-5 my-3">
    <h3>Our Service</h3>
    <form asp-action="Create" method="post" enctype="multipart/form-data">
        <div class="form-group">

            <label for="Icon">Icon</label>
            <input class="form-control" asp-for="Icon">
            <span class="text-danger" asp-validation-for="Icon"></span>

            <label for="Name">Name</label>
            <input class="form-control" asp-for="Name">
            <span class="text-danger" asp-validation-for="Name"></span>

            <label for="Desc">Desc</label>
            <input class="form-control" asp-for="Desc">
            <span class="text-danger" asp-validation-for="Desc"></span>


        </div>
        <a class="btn btn-primary" asp-controller="OurService" asp-action="Index">Back</a>
        <a class="btn btn-primary" asp-controller="OurService" asp-action="Create">Reset</a>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

Creative_blog/Areas/AdminArea/Views/OurService/Detail.cshtml
@model OurService
@{
    ViewData["Title"] = "Detail";
}

<div class="container">
    <div class="container-fluid my-3 mx-3">
        <div class="table-responsive pt-3">

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            Icon
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Desc
                        </th>


                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <div class="box-item">
                                <i class="@Model.Icon"></i>

                            </div>
                        </td>
                        <td>
                            @Model.Name
                        </td>
                        <td>
                            @Model.Desc
                        </td>


                    </tr>


                </tbody>
            </table>
        </div>
    </div>
</div>

Creative_blog/Areas/AdminArea/Views/OurService/Edit.cshtml
@model OurService
@{
    ViewData["Title"] = "Create";
}



<div class="container-fluid mx-5 my-3">
    <h3>Our Service Edit</h3>
    <form asp-action="Edit" method="post" enctype="multipart/form-data">
        <div class="form-group">

            <label for="Icon">Icon</label>
            <input class="form-control" asp-for="Icon">
            <span class="text-danger" asp-validation-for="Icon"></span>

            <label for="Name">Name</label>
            <input class="form-control" asp-for="Name">
            <span class="text-danger" asp-validation-for="Name"></span>

            <label for="Desc">Desc</label>
            <input class="form-control" asp-for="Desc">
            <span class="text-danger" asp-validation-for="Desc"></span>


        </div>
        <a class="btn btn-primary" asp-controller="OurService" asp-action="Index">Back</a>
        <a class="btn btn-primary" asp-controller="OurService" asp-action="Create">Reset</a>
        <button type="submit" class="btn btn-primary">Edit</button>
    </form>
</div>

Creative_blog/Areas/AdminArea/Views/OurService/Index.cshtml
@model Paginate<OurServiceListVM>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="container-fluid my-3 mx-3">
        <div class="table-responsive pt-3">
            <div class="create-btn mb-3">
                <a asp-area="AdminArea" asp-controller="OurService" asp-action="Create" class="btn btn-success"><i class="fa-solid fa-plus"><h1></h1></i></a>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            Icon
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Desc
                        </th>


                        <th style="text-align: center;">
                            Settings
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Datas)
                    {
                        <tr>
                            <td>
                                <div class="box-item">
                                    <i class="@item.Icon"></i>

                                </div>
                            </td>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @item.Desc
                            </td>

                            <td style="text-align: center;">
                                <a asp-action="Detail" asp-route-id="@item.Id" class="btn btn-primary"><i class="mdi mdi-information mx-0">D</i></a>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary"><i class="mdi mdi-table-edit"></i>E</a>
                                <form style="display: inline-block;" asp-action="Delete" asp-route-id="@item.Id" method="post">
                                    <button type="submit" class="btn btn-danger"><i class="mdi mdi-delete-forever"></i>R</button>
                                </form>
                            </td>
                        </tr>




                    }

                </tbody>
                    
            </table>
            <nav aria-label="...">
                <ul class="pagination">
                    <li class="page-item @(Model.HasPrevious == false ? "disabled":"")">
                        <a class="page-link" asp-action="Index" asp-route-page="@(Model.CurrentPage - 1)">
                            Previous
                        </a>
                    </li>
                    @for (int i = 1; i <= Model.TotalPage; i++)
                    {
                        <li class="page-item @(i==Model.CurrentPage ? "disabled":"")"><a class="page-link" asp-action="Index" asp-route-page="@i">@i</a></li>
                    }
                    
                    
                    <li class="page-item @(Model.HasNext == true ? "" :"disabled")">
                        <a class="page-link" asp-action="Index" asp-route-page="@(Model.CurrentPage + 1)">
                            Next
                        </a>
                    </li>
                </ul>
                
            </nav>
        </div>
    </div>
</div>