Creative_blog/Controllers/BlogDetailController.cs
using Creative_blog.Data;
using Creative_blog.Models;
using Creative_blog.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Creative_blog.Controllers
{
    public class BlogDetailController : Controller
    {
        private readonly AppDbContext _context;

        public BlogDetailController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int? id)
        {
            if (id is null) return BadRequest();

            Blog blog = await _context.Blogs.Include(m => m.Comments)
                .FirstOrDefaultAsync(m => m.Id == id);


            if (blog is null) return NotFound();

            IEnumerable<Comment> comments = await _context.Comments.ToListAsync();


            List<Blog> blogs = await _context.Blogs.ToListAsync();
            


            BlogDetailVM blogVM = new BlogDetailVM
            {
                blog = blog,
                comments = (List<Comment>)comments
            };

            return View(blogVM);
        }


        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Comment(Comment newComment)
        {
            var commentCount = await _context.Comments.CountAsync();
            string unknown = "Anonymous";

            if (User.Identity.Name != null)
            {
                unknown = User.Identity.Name.ToString();
            }

            Comment comment = new Comment()
            {
                Content = newComment.Content,
                BlogId = newComment.BlogId,
                UserName = unknown,
                Datetime = DateTime.Now.ToString()
            };

            await _context.Comments.AddAsync(comment);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", new { id = comment.BlogId });
        }



    }
}

Creative_blog/Views/BlogDetail/Index.cshtml
@model BlogDetailVM
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Creative Blog</title>
    <!--
      - favicon
    -->
    <link rel="shortcut icon" href="~/assets/blog/assets/images/favicon.ico" type="image/x-icon">

    <!--
      - custom css link
    -->
    <link rel="stylesheet" href="~/assets/blog/assets/css/style2.css">

    <!--
      - google font link
    -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;900&display=swap" rel="stylesheet">
</head>

<body class="light-theme">

    <!--
      - #HEADER
    -->

    <header>

        <div class="container">

            <nav class="navbar">

                <a asp-controller="Home" asp-action="Index">
                    <img src="~/assets/imgs/logo.png"  width="50" height="50" class="logo-light">
                    <img src="~/assets/imgs/logo.png"  width="50" height="50" class="logo-dark">
                </a>

                <div class="btn-group">

                    <button class="theme-btn theme-btn-mobile light">
                        <ion-icon name="moon" class="moon"></ion-icon>
                        <ion-icon name="sunny" class="sun"></ion-icon>
                    </button>

                    <button class="nav-menu-btn">
                        <ion-icon name="menu-outline"></ion-icon>
                    </button>

                </div>

                <div class="flex-wrapper">

                    <ul class="desktop-nav">

                        <li>
                            <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                        </li>



                        <li>
                            <a asp-controller="SendMessage" asp-action="Index" class="nav-link">Contact</a>
                        </li>

                    </ul>

                    <button class="theme-btn theme-btn-desktop light">
                        <ion-icon name="moon" class="moon"></ion-icon>
                        <ion-icon name="sunny" class="sun"></ion-icon>
                    </button>

                </div>

                <div class="mobile-nav">

                    <button class="nav-close-btn">
                        <ion-icon name="close-outline"></ion-icon>
                    </button>

                    <div class="wrapper">

                        <p class="h3 nav-title">Main Menu</p>

                        <ul>
                            <li class="nav-item">
                                <a href="#" class="nav-link">Home</a>
                            </li>

                            <li class="nav-item">
                                <a href="#" class="nav-link">About Me</a>
                            </li>

                            <li class="nav-item">
                                <a href="#" class="nav-link">Contact</a>
                            </li>
                        </ul>

                    </div>

                    <div>

                        <p class="h3 nav-title">Topics</p>

                        <ul>
                            <li class="nav-item">
                                <a href="#" class="nav-link">Database</a>
                            </li>

                            <li class="nav-item">
                                <a href="#" class="nav-link">Accessibility</a>
                            </li>

                            <li class="nav-item">
                                <a href="#" class="nav-link">Web Performance</a>
                            </li>
                        </ul>

                    </div>

                </div>

            </nav>

        </div>

    </header>





    <main>

        <!--
          - #HERO SECTION
        -->







        <div class="main">

            <div class="container">

                <!--
                  - BLOG SECTION
                -->
                <div class="blog">
                        
                    <div class="blog-card-group">

                        
                        
                            <div class="blog-card Database">

                                <div class="blog-card-banner">
                                    <img src="~/assets/blog/assets/images/@Model.blog.Image" alt="Building microservices with Dropwizard, MongoDB & Docker"
                                     width="250" class="blog-banner-img">
                                </div>

                                <div class="blog-content-wrapper">
                                <div class="wrapper-flex">

                                    <div class="profile-wrapper">
                                        <img src="~/assets/blog/assets/images/User-avatar.svg.png" width="50">
                                    </div>

                                    <div class="wrapper">
                                        <a href="#" class="h4">Created by Admin</a>

                                        <p class="text-sm">
                                            <time datetime="2022-01-17">Jan 11, 2022</time>

                                        </p>
                                    </div>

                                </div>

                                    <h3>
                                        <a class="h2" >
                                        @Model.blog.Name
                                        </a>
                                    </h3>

                                <a class="blog-text" >
                                    @Model.blog.Desc
                                    </a>

                                    

                                </div>

                            </div>

                            @foreach (var comment in Model.comments.Where(m=>m.BlogId==Model.blog.Id))
                        {
                            <div class="blog-card comment">
                            <div class="wrapper-flex">

                                <div class="profile-wrapper">
                                    <img src="~/assets/blog/assets/images/User-avatar.svg.png" width="50">
                                </div>

                                <div class="wrapper">
                                    <a class="h4">@comment.UserName</a>

                                    <p class="text-sm">
                                        <time datetime="2022-01-17">@comment.Datetime</time>
                                    </p>
                                </div>
                            </div>
                                <a>@comment.Content</a>
                            </div>
                        }
                            




                            <form asp-controller="BlogDetail" asp-action="Comment" method="post" enctype="multipart/form-data">
                                    @*<input type="hidden" value="@Model.Blog.Id"/>*@
                                    <div class="comment-post-box">
                                        <div class="row">
                                            <div class="col-12">

                                                <input type="hidden" asp-for="@Model.comments.FirstOrDefault().BlogId" value="@Model.blog.Id" />

                                                <label for="content"></label>
                                                <input class="form-control" id="exampleFormControlTextarea1" asp-for="@Model.comments.FirstOrDefault().Content" value= placeholder="Add your comment about blog"/>
                                            </div>
                                            @*<div class="col-lg-4 col-md-4">
                                                <label>Name</label>
                                                <input type="text" class="coment-field" placeholder="Name">
                                            </div>
                                            <div class="col-lg-4 col-md-4">
                                                <label>Email</label>
                                                <input type="text" class="coment-field" placeholder="Email">
                                            </div>
                                            <div class="col-lg-4 col-md-4">
                                                <label>Website</label>
                                                <input type="text" class="coment-field" placeholder="Website">
                                            </div>
                                            <div class="col-12">
                                                <div class="coment-btn">

                                                </div>
                                            </div>*@
                                        </div>
                                    </div>
                                    <button class="btn btn-outline-success rounded" type="submit">Share</button>
                                </form>


                    </div>


                </div>





                <!--
                  - ASIDE
                -->


            </div>

        </div>

    </main>





    <!--
      - #FOOTER
    -->

    





    <!--
      - custom js link
    -->
    <script src="~/assets/blog/assets/js/script.min.js"></script>

    <!--
      - ionicon link
    -->
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>



    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

</html>